export const skillGroups = [
  {
    category: 'ML & Forecasting',
    items: [
      'Python',
      'PySpark',
      'XGBoost',
      'LightGBM',
      'Prophet',
      'ARIMA/SARIMA',
      'Hierarchical Forecasting',
      'Scikit-learn',
      'SHAP',
    ],
  },
  {
    category: 'Optimization & Simulation',
    items: [
      'Linear Programming',
      'MILP (PuLP)',
      'SciPy',
      'EOQ',
      'Safety Stock',
      'Monte Carlo',
      'SimPy',
      'RL-based Pricing',
    ],
  },
  {
    category: 'MLOps & Cloud',
    items: [
      'Oracle OCI Data Science',
      'AWS SageMaker',
      'AWS S3/Lambda/SES',
      'Azure ML',
      'MLflow',
      'Docker',
      'GitHub Actions',
    ],
  },
  {
    category: 'Data & BI',
    items: [
      'SQL (CTEs, Window Functions)',
      'Power BI',
      'Tableau',
      'Streamlit',
      'ERP/IoT Pipelines',
      'REST APIs',
    ],
  },
  {
    category: 'Supply Chain Domain',
    items: [
      'S&OP',
      'Demand Forecasting',
      'Procurement Analytics',
      'Supplier Risk',
      'Inventory Optimization',
      'Network Planning',
      'SAP IBP / o9 / Kinaxis (awareness)',
    ],
  },
  {
    category: 'Web & Full Stack',
    items: [
      'React.js',
      'Node.js',
      'Express.js',
      'MongoDB (NoSQL)',
      'Redis',
      'REST APIs',
      'HTML · CSS · JavaScript',
      'Streamlit',
    ],
  },
  {
    category: 'Collaboration & Leadership',
    items: [
      'Cross-functional Stakeholder Communication',
      'S&OP Meeting Facilitation',
      'Translating Analytics to Business Decisions',
      'Presentation & Data Storytelling',
      'Agile / Scrum Workflows',
      'Mentoring & Knowledge Transfer',
    ],
  },
]
